AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/Documentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericLiterals:
  Exclude:
    - '**/*_spec.rb'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'mnemosyne.gemspec'
    - '**/*_spec.rb'
