AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'deploy/**/*'
  TargetRubyVersion: 2.4


Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false


Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - '**/*_spec.rb'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/SignalException:
  EnforcedStyle: only_raise


Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/*.rake'

Metrics/LineLength:
  Exclude:
    - 'mnemosyne.gemspec'
    - '**/*_spec.rb'
