dist: trusty
sudo: true
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - '2.4.1'
env:
  - TIMESCALEDB=false
addons:
  postgresql: '9.6'
before_install:
  - gem update --system
  - gem install bundler
  - bundle config github.https true
before_script:
  - bundle exec rails db:create:all
  - bundle exec rails db:migrate
script:
  - bundle exec rake rubocop
  - bundle exec rake spec
