dist: trusty
sudo: false
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - '2.4.1'
addons:
  postgresql: '9.5'
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rails db:create:all
  - bundle exec rails db:migrate
script:
  - bundle exec rake rubocop
  - bundle exec rake spec
