language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - '2.4.0'
addons:
  postgresql: '9.6'
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rails db:create:all
  - bundle exec rails db:migrate
