# Restart webpack-dev-server if you make changes here
default: &default
  enabled: true
  host: localhost
  port: 9000

development:
  <<: *default
  enabled: false

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
