# Restart webpack-watcher or webpack-dev-server if you make changes here
default: &default
  config: config/webpack
  entry: .
  output: public/assets
  manifest: manifest.json
  node_modules: node_modules
  source: app/assets
  public: assets

development:
  <<: *default

test:
  <<: *default
  manifest: manifest-test.json

production:
  <<: *default
