# Configure additional pipeline steps

development:
  load:
    # Collect and send metrics to InfluxDB
    # - Metrics::Influx:
    #     database: mnemosyne
    #     host: localhost
    #     async: true
    #
    # Ignore all traces with an origin UUID
    # of `00000000-0000-0000-0000-000000000000`.
    # - Filter::NullOrigin

production:
