# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2209d8b8d8f71532a4f26f4f70e69ebd65303ace21f430c9b89aafa9b2703678fe0f3ebdb68e7c0fbe1a5189b443ec046f53245a4ee5faa9138f4cd3f7e97785

test:
  secret_key_base: 55ecf3ee554f9cc5f54919ac4cd28fb80b9368193b1471f81b93819a66c9d9e9e005b3cece572447ec3132a8f884f647aa109e449c56bcaa76a1d071bbd0b051

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Blub: This file will be overridden on deploy anyway.
production:
  secret_key_base: 2209d8b8d8f71532a4f26f4f70e69ebd65303ace21f430c9b89aafa9b2703678fe0f3ebdb68e7c0fbe1a5189b443ec046f53245a4ee5faa9138f4cd3f7e97785
