# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source: app/assets
  output: public/assets
  public: assets
  manifest: manifest.json
  public_output_path: assets

development:
  <<: *default

  dev_server:
    host: localhost
    port: 9000

test:
  <<: *default

production:
  <<: *default
